export const dublinCities = [
  "Artane",
  "Balbriggan",
  "Ballsbridge",
  "Ballymun",
  "Blackrock",
  "Blanchardstown",
  "Cabinteely",
  "Castleknock",
  "Clondalkin",
  "Clontarf",
  "Donnybrook",
  "Drimnagh",
  "Dublin City Centre",
  "Dún Laoghaire",
  "Finglas",
  //   "Howth",
  //   "Lucan",
  //   "Malahide",
  //   "Rathmines",
  //   "Swords",
  //   "Tallaght",
  //   "Terenure",

  //Nigeria
  "Lagos",
  "Delta",
  "Abuja",
  "Port Harcourt",
  "Osun",
  "Oyo",
].map((city) => ({ value: city.toLowerCase(), label: city }));
