import React, { SVGAttributes } from "react";
export type TIcon = SVGAttributes<SVGElement>;
export type TRenderSvg = (args: TIcon) => React.ReactNode;
export type TIconNames =
  | "dashboardIcon"
  | "restaurantIcon"
  | "userIcon"
  | "reportIcon"
  | "settingsIcon"
  | "externalLinkIcon"
  | "mapPinIcon"
  | "linkIcon"
  | "calendarIcon"
  | "videoIcon"
  | "flameIcon"
  | "cancelModalIcon"
  | "bookIcon"
  | "carIcon"
  | "tiktokIcon"
  | "calendarIcon"
  | "bookCalendarIcon"
  | "groupUserIcon"
  | "arrowdownIcon"
  | "worldIcon"
  | "menuIcon"
  | "arrowBackIcon"
  | "restaurantLocationIcon"
  | "restaurantTimeIcon"
  | "restaurantReversationIcon"
  | "restaurantTiktokIcon"
  | "postCalendarIcon"
  | "globeIcon"
  | "deactivateIcon"
  | "saveIcon"
  | "statusIcon"
  | "warningIcon"
  | "googleIcon"
  | "binIcon"
  | "pencilIcon"
  | "personIcon";
